### ISSUE TITLE
Needs New Limitations

### ISSUE THREAD

**Issue by J4ol** [TurboWarp/unpackager#6]
It Would Be Good If There Was Someway to Stop Unpacking Like A Comment That Says "UNPACKDATA=FALSE" Should be Able To Stop It. (I have a project that I do not want to be unpacked)

**Comment by J4ol** [comment]
Or In https://packager.turbowarp.org at a "Anit-Unpacking" Button

**Comment by J4ol** [comment]
I Just Made Something Called Codebomb That Stops The unpacker By Crashing/Corrupting Code

**Comment by GarboMuffin** [comment]
We've mentioned this elsewhere: We will not be adding such an option because it fundamentally would not change the fact that the projects can be unpackaged. Remember: Everything in TurboWarp is open source, so someone could simply remove the unpackager's check to see if the project opted out of being unpackaged!

If this really bothers you, you are on your own to implement DRM.
