### ISSUE TITLE
Take this down. Immediately.

### ISSUE THREAD

**Issue by LIZARD-OFFICIAL** [TurboWarp/unpackager#7]
This just makes your app forcibly open source.
What if i cannot copyright my project? 
Turbowarp should make a setting to disable unpackaging or remove this.

**Comment by GarboMuffin** [comment]
Please see the text at the bottom of https://turbowarp.github.io/unpackager/

> This just makes your app forcibly open source.

That's not how copyright law works

> What if i cannot copyright my project?

Sounds like you have bigger issues anyways

>  Turbowarp should make a setting to disable unpackaging or remove this.

This is infeasible and any attempts can be trivially bypassed. Deleting the unpackager would only provide a facade -- your project would not be any safer.

**Comment by GarboMuffin** [comment]
"What if i cannot copyright my project?" is a particularly interesting question to me actually, because I'm not entirely sure what circumstances that would imply?

The only instance I can think of is if your project is significantly based on the work of others, in which case worrying about the unpackager is a bit silly

(Remember - you don't need to register for copyright [at least in the US] - it's automatic)

**Comment by LIZARD-OFFICIAL** [comment]
> "What if i cannot copyright my project?" is a particularly interesting question to me actually, because I'm not entirely sure what circumstances that would imply?
> 
> The only instance I can think of is if your project is almost entirely based on the work of others, in which case worrying about the unpackager is a bit silly
> 
> (Remember - you don't need to register for copyright [at least in the US] - it's automatic)

Well Im not in US.

**Comment by GarboMuffin** [comment]
my understanding is that basically no where on the planet is registering necessary for copyright

and again, if you don't actually own the copyright for the project, you have much bigger issues than the unpackager.
