### ISSUE TITLE
File not unpackaging

### ISSUE THREAD

**Issue by error404unreachable** [TurboWarp/unpackager#9]
I tried both of the following:
[ezyzip.zip](https://github.com/TurboWarp/unpackager/files/15063746/ezyzip.zip)
and https://github.com/error404unreachable/error404unreachable.github.io/blob/main/Tidal%20Wave%20LDM.html (converted to html through cloud convert)

Neither worked

**Comment by GarboMuffin** [comment]
the HTML file you gave unpackages perfectly fine, don't put it into any converters, just right click the link > save as > put that into the unpackager

**Comment by GarboMuffin** [comment]
if you can't do that just download this and extract [Tidal Wave LDM.zip](https://github.com/TurboWarp/unpackager/files/15064299/Tidal.Wave.LDM.zip)

**Comment by 1324ryaLol** [comment]
how to to do it if its in itch.io i cant unpackage this https://coolskull212again.itch.io/sprunkiretake
i have the zip file btw

**Comment by GarboMuffin** [comment]
You should open a new issue for new bugs, not try to comment on something that was already closed.

Anyways. This is more complicated because the zip is the installer not the unpacked files like usual. So I did this manually for you, here is the file you're looking for: https://static.muffin.ink/sb3fix-9-comment.sb3. Deleting that link in a couple days so be quick.
